; Script originally generated by the HM NIS Edit Script Wizard,
; Then heavily modified by Justin Dearing <zippy1981@gmail.com>

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "WinAndroStack"
!define PRODUCT_VERSION "0.1"
!define PRODUCT_PUBLISHER "Secure Data Software"
!define PRODUCT_WEB_SITE "http://www.andromeda-project.org/"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\xampp-win32-1.7.0-installer.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; No point in compressing already compressed binary installers.
SetCompress off
;SetCompressor lzma

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!define MUI_LICENSEPAGE_CHECKBOX
!insertmacro MUI_PAGE_LICENSE "..\\andro\gpl.txt"
; Components page
!insertmacro MUI_PAGE_COMPONENTS
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$TEMP\WinAndro\xampp-win32-1.7.0-installer.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"

; Reserve files
!insertmacro MUI_RESERVEFILE_INSTALLOPTIONS

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "WinAndroStack-Setup.exe"
InstallDir "$PROGRAMFILES\WinAndroStack"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show


Section "Base" SEC00
  SetOutPath "$TEMP\WinAndro"
  SetOverwrite on
  CreateDirectory "$SMPROGRAMS\Andromeda"
  CreateShortCut "$SMPROGRAMS\Andromeda\WinAndroStack.lnk" "$TEMP\WinAndro\xampp-win32-1.7.0-installer.exe"
  CreateShortCut "$SMPROGRAMS\Andromeda\SecDat.lnk" "http://secdat.com/"
SectionEnd

Section "XAMPP" SEC01
  File "xampp-win32-1.7.0-installer.exe"
  ExecWait "xampp-win32-1.7.0-installer.exe /S"
  Delete "$TEMP\WinAndro\xampp-win32-1.7.0-installer.exe"
SectionEnd

Section "ActivePerl" SEC02
  File "ActivePerl-5.8.9.825-MSWin32-x86-288577.msi"
  ExecWait "msiexec /i ActivePerl-5.8.9.825-MSWin32-x86-288577.msi /passive"
  Delete "$TEMP\WinAndro\ActivePerl-5.8.9.825-MSWin32-x86-288577.msi"
SectionEnd

Section "PHP" SEC03
  File "php-5.2.8-win32-installer.msi"
  ExecWait "msiexec /i php-5.2.8-win32-installer.msi /passive ADDLOCAL=Manual,PEAR,ext_php_pgsql"
  Delete "$TEMP\WinAndro\php-5.2.8-win32-installer.msi"
SectionEnd

Section "Postgresql" SEC04
  File 'postgresql-8.3.5-1\postgresql-8.3.msi'
  File 'postgresql-8.3.5-1\postgresql-8.3-int.msi'
  File 'postgresql-8.3.5-1\vcredist_x86.exe'
  ExecWait 'postgresql-8.3.5-1\vcredist_x86.exe /q:a /c:"msiexec /i vcredist.msi /qb!"'
  ExecWait 'msiexec /i postgresql-8.3.5-1\postgresql-8.3.msi /q'
  Delete '$TEMP\WinAndro\postgresql-8.3.5-1\vcredist_x86.exe'
  Delete '$TEMP\WinAndro\postgresql-8.3.5-1\postgresql-8.3.msi'
  Delete '$TEMP\WinAndro\postgresql-8.3.5-1\postgresql-8.3-int.msi'
SectionEnd

Section -AdditionalIcons
  SetOutPath $INSTDIR
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\Andromeda\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\Andromeda\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$TEMP\WinAndro\xampp-win32-1.7.0-installer.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$TEMP\WinAndro\xampp-win32-1.7.0-installer.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd

; Section descriptions
!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC00} "Shortcuts and such"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC01} "Apache Friends Xampp stack 1.7.0"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC02} "ActivePerl 5.8.9.825"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC03} "PHP 5.2.8 (for installing with IIS.)"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC04} "Postgresql 8.5"
!insertmacro MUI_FUNCTION_DESCRIPTION_END


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) was successfully removed from your computer."
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Are you sure you want to completely remove $(^Name) and all of its components?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  ExecWait "msiexec.exe /x {537A9973-4BD1-404F-A89F-A92E03DD9CC9} /passive" ; PHP 5.2.8
  ExecWait "msiexec.exe /x {927B2033-F432-4CD8-B0D0-2945B414B95F} /passive" ; ActivePerl 5.8.9.825
  ExecWait "msiexec.exe /x {B823632F-3B72-4514-8861-B961CE263224} /passive" ; Postgresql 8.3
  
  ; Uninstall xampp
  ReadRegStr $0 HKLM 'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\xampp' "UninstallString"
  MessageBox MB_OK $0
  IfFileExists $0 0 +2
    ExecWait "$0 /S"

  Delete "$SMPROGRAMS\Andromeda\Uninstall.lnk"
  Delete "$SMPROGRAMS\Andromeda\Website.lnk"
  Delete "$SMPROGRAMS\Andromeda\WinAndroStack.lnk"

  RMDir "$TEMP\WinAndro"
  RMDir "$SMPROGRAMS\Andromeda"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd