<?php
class cms extends x_table2 {
    function main() {
        # We'll need this here and there
        $page=urldecode(gp('gp0'));
        $pagex=substr($page,0,strlen($page)-5);
        $file=str_replace(' ','',$page);
        $file=strtolower($file);
        
        # Before anything, see if a comment was posted.
        if(gp('x4inp_comments_notes')<>'') {
            $row = aFromGp('x4inp_comments_');
            $row['page'] = substr($page,0,strlen($page)-5);
            $row['notes'] = str_replace('<','&lt;',$row['notes']);
            $row['notes'] = str_replace('>','&gt;',$row['notes']);
            $row['notes'] = str_replace('[b]','<b>',$row['notes']);
            $row['notes'] = str_replace('[/b]','</b>',$row['notes']);
            $row['notes'] = str_replace('[i]','<i>',$row['notes']);
            $row['notes'] = str_replace('[/i]','</i>',$row['notes']);
            $row['notes'] = str_replace('[pre]','<pre>',$row['notes']);
            $row['notes'] = str_replace('[/pre]','</pre>',$row['notes']);
            
            if(gp('first_name')<>'') {
                emailSend('andromeda@secdat.com','Comment Discarded'
                    ,"This comment was discarded:\n"
                    ."\nnickname: ".$row['name']
                    ."\nemail:    ".$row['email']
                    ."\n\n"
                    .$row['notes']
                );
            }
            else {
                SQLX_Insert('comments',$row);
                if(!Errors()) {
                    emailSend('andromeda@secdat.com','New User Comment'
                        ,'A new user comment awaits moderation'
                        ."\n\nnickname: ".$row['name']
                        ."\nemail:    ".$row['email']
                        ."\n\n"
                        .$row['notes']
                    );
                }
            }
        }
        
        # These are child topics on the left
        $fileleft = fsDirTop().'files/'.$file.'.left.html';
        if(file_exists($fileleft)) {
            global $html;
            $html['left'] 
                ='<div class="moduletable-hilite3">'
                .file_get_contents($fileleft)
                ."</div>";
        }
        
        # The main content is read directly in here.  It was
        # generated by the robophp.php program.
        include(fsDirTop().'files/'.$file);
        
        # Now we run out user comments already approved
        $vcomments = ddView('comments');
        $comments = SQL_AllRows(
            "Select * from $vcomments
              where page = ".SQLFC($pagex)."
                and coalesce(flag_moderated,'N')='Y'
              order by comment"
        );
        
        # Begin with a form that will hold the inputs.  Turn off
        # the regular form also.
        vgaSet('NOFORM',true);
        $div = html('form');
        $div->hp['method'] = 'POST';
        $div->hp['action'] = baseUrl().'pages/cms/'.urlencode($page);
        $div->hr();
        $div->h('h3','User Comments');
        foreach($comments as $comment) {
            $dc = $div->h('div');
            $dc->hp['style'] = 'border: 1px solid #606060;
                border-bottom: 0;
                padding: 5px;
                background-color: #c0c0c0';
            $dc->setHtml(
                "Submitted by ".$comment['name'].', '
                .date('l F j, Y',dEnsureTs($comment['ts_ins']))
            );
            $dc=$div->h('div');
            $dc->hp['style'] = 'border: 1px solid #606060;
                padding: 5px;
                background-color: #E0E0E0';
            $comment['notes'] = str_replace("\r","\n",$comment['notes']);
            $comment['notes'] = str_replace("\n\n\n\n","\n\n",$comment['notes']);
            $comment['notes'] = str_replace("\n","<br/>",$comment['notes']);
            $dc->setHtml($comment['notes']);
            $div->br(2);
        }
        if(count($comments)==0) {
            $div->h('p','There are no user comments yet on this page.');
        }
        $div->hr();

        # now grab the data dictionary for user comments
        $dd = ddTable('comments');
        
        $div->h('h3','Add A Comment');
        $div->h('div','<b>Comments will not appear until after they are
            moderated.  Comments are usually moderated within a few hours
            on weekdays, but may take longer on weekends and holidays.
            </b><br/><br/>'
        );
        $div->h('div','Name or nickname: (This will appear with your comment)');
        $input = input($dd['flat']['name']);
        $div->addChild($input);
        $div->br(2);
        
        $input = input($dd['flat']['name']);
        $input->hp['name'] = $input->hp['id'] = 'first_name';
        $input->hp['value'] = '';
        $input->hp['style'] = 'display: none;';
        $div->addChild($input);
        
        $div->h('div','Email (this will never be displayed)');
        $input = input($dd['flat']['email']);
        $div->addChild($input);
        $div->br(2);

        $div->h('div','Enter your comment here.  Use [b] and [/b] for
            bold, [i] and [/i] for italic, and [pre] and [/pre] for
            code samples.  All literal HTML and PHP that you enter will
            be esacped out and displayed as you enter it.');
        $input = input($dd['flat']['notes']);
        $div->addChild($input);

        $div->br(2);
        $inp=$div->h('input');
        $inp->hp['type'] = 'submit';
        $inp->hp['value'] = 'Submit';
        
        $div->render();
    }
}
?>
